# Generated by Django 5.0.6 on 2024-06-10 07:06

import AxomApp.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(default='', max_length=255)),
                ('content11', models.TextField()),
                ('content12', models.TextField()),
                ('image1', models.ImageField(upload_to='AboutUs_Images/')),
                ('title2', models.CharField(default='', max_length=255)),
                ('content2', models.TextField()),
                ('title3', models.CharField(default='', max_length=255)),
                ('content3', models.TextField()),
                ('image4', models.ImageField(upload_to='AboutUs_Images/')),
            ],
        ),
        migrations.CreateModel(
            name='AddBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='blog/')),
                ('blog_image_caption', models.CharField(max_length=255)),
                ('blog_description_title', models.TextField()),
                ('blog_description', models.TextField()),
                ('description_image', models.ImageField(upload_to='blog/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255)),
                ('page_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carousal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard_Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='download_images')),
                ('data_sheet', models.FileField(upload_to='download_files')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sitedescription', models.TextField()),
                ('address1', models.CharField(default=' ', max_length=255)),
                ('address2', models.CharField(default=' ', max_length=255)),
                ('country', models.CharField(default=' ', max_length=100)),
                ('city', models.CharField(default=' ', max_length=255)),
                ('zipcode', models.CharField(default=' ', max_length=20)),
                ('sitelogo', models.ImageField(blank=True, upload_to='Site_logo/')),
                ('browsersitelogo', models.ImageField(blank=True, upload_to=AxomApp.models.upload_to)),
                ('primaryemail', models.EmailField(default=' ', max_length=254)),
                ('secondaryemail', models.EmailField(default=' ', max_length=254)),
                ('replaytoemail', models.EmailField(default=' ', max_length=254)),
                ('primarycontactnumber', models.CharField(default=' ', max_length=20)),
                ('secondarycontactnumber', models.CharField(default=' ', max_length=20)),
                ('tertiarycontactnumber', models.CharField(default=' ', max_length=20)),
                ('facebookurl', models.CharField(default=' ', max_length=255)),
                ('twitterurl', models.CharField(default=' ', max_length=255)),
                ('instagramurl', models.CharField(default=' ', max_length=255)),
                ('skypeurl', models.CharField(default=' ', max_length=255)),
                ('linkedinurl', models.CharField(default=' ', max_length=255)),
                ('metakeywords', models.CharField(default=' ', max_length=255)),
                ('metadescription', models.CharField(default=' ', max_length=50000)),
                ('googleanalyticscode', models.CharField(default=' ', max_length=50000)),
                ('cssinput', models.CharField(default=' ', max_length=255)),
                ('jsinput', models.CharField(default=' ', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='carousal_background_images/')),
                ('title1', models.CharField(default='', max_length=255)),
                ('content11', models.TextField()),
                ('content12', models.TextField()),
                ('image1', models.ImageField(upload_to='Home_Images/')),
                ('title2', models.CharField(default='', max_length=21)),
                ('content21', models.TextField(max_length=70)),
                ('content22', models.TextField(max_length=70)),
                ('image4', models.ImageField(upload_to='Home_Images/')),
                ('title3', models.CharField(default='', max_length=255)),
                ('content3', models.TextField()),
                ('title4', models.CharField(default='', max_length=255)),
                ('content41', models.TextField()),
                ('content42', models.TextField()),
                ('image8', models.ImageField(upload_to='Home_Images/')),
                ('title5', models.CharField(default='', max_length=21)),
                ('content51', models.TextField(max_length=70)),
                ('content52', models.TextField(max_length=70)),
                ('image11', models.ImageField(upload_to='Home_Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='product_carousal_images')),
            ],
        ),
        migrations.CreateModel(
            name='MapCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Contact_page_images')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sustainable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(default='', max_length=255)),
                ('content11', models.TextField()),
                ('content12', models.TextField()),
                ('title2', models.CharField(default='', max_length=255)),
                ('content21', models.TextField()),
                ('content22', models.TextField()),
                ('image1', models.ImageField(upload_to='sustainable_images')),
                ('image2', models.ImageField(upload_to='sustainable_images')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AxomApp.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('watts', models.CharField(max_length=255)),
                ('cct', models.CharField(max_length=255)),
                ('dimmable_system', models.CharField(max_length=255)),
                ('lumen_efficiency', models.CharField(max_length=255)),
                ('fixing', models.CharField(max_length=255)),
                ('led_source', models.CharField(max_length=255)),
                ('ip_rating', models.CharField(max_length=255)),
                ('life_span', models.CharField(max_length=255)),
                ('is_selected', models.BooleanField(default=False)),
                ('displayimage1', models.ImageField(upload_to='products/')),
                ('displayimage2', models.ImageField(upload_to='products/')),
                ('displayimage3', models.ImageField(upload_to='products/')),
                ('email', models.EmailField(max_length=254)),
                ('data_sheet', models.FileField(upload_to='product_files/')),
                ('ldf_file', models.FileField(upload_to='product_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image1', models.ManyToManyField(related_name='product_carousal_images', to='AxomApp.image')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AxomApp.subcategory')),
            ],
        ),
    ]
